version: '3.4'

services:
  bookstore.server.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  bookstore.client:
    ports:
      - "5001:3000"
    stdin_open: true 
    tty: true        
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "81:81"